{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kmortem.serviceAccountName" . }}
  namespace: {{ include "kmortem.namespace" . }}
  labels:
    {{- include "kmortem.labels" . | nindent 4 }}
{{- end }}
