apiVersion: v2
name: kmortem
description: Kubernetes operator that captures forensic NodeReport records when nodes terminate
type: application
version: 0.0.5
appVersion: "v0.0.5"
keywords:
  - kubernetes
  - operator
  - node
  - forensics
home: https://github.com/thomaschaplin/kmortem
sources:
  - https://github.com/thomaschaplin/kmortem
maintainers:
  - name: thomaschaplin
    url: https://github.com/thomaschaplin
