//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchivalRecord) DeepCopyInto(out *ArchivalRecord) {
	*out = *in
	if in.ArchivedAt != nil {
		in, out := &in.ArchivedAt, &out.ArchivedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchivalRecord.
func (in *ArchivalRecord) DeepCopy() *ArchivalRecord {
	if in == nil {
		return nil
	}
	out := new(ArchivalRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionRecord) DeepCopyInto(out *ConditionRecord) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionRecord.
func (in *ConditionRecord) DeepCopy() *ConditionRecord {
	if in == nil {
		return nil
	}
	out := new(ConditionRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMetadata) DeepCopyInto(out *InstanceMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMetadata.
func (in *InstanceMetadata) DeepCopy() *InstanceMetadata {
	if in == nil {
		return nil
	}
	out := new(InstanceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMetadata) DeepCopyInto(out *NodeMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMetadata.
func (in *NodeMetadata) DeepCopy() *NodeMetadata {
	if in == nil {
		return nil
	}
	out := new(NodeMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReport) DeepCopyInto(out *NodeReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReport.
func (in *NodeReport) DeepCopy() *NodeReport {
	if in == nil {
		return nil
	}
	out := new(NodeReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReportList) DeepCopyInto(out *NodeReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReportList.
func (in *NodeReportList) DeepCopy() *NodeReportList {
	if in == nil {
		return nil
	}
	out := new(NodeReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReportSpec) DeepCopyInto(out *NodeReportSpec) {
	*out = *in
	if in.TerminationTime != nil {
		in, out := &in.TerminationTime, &out.TerminationTime
		*out = (*in).DeepCopy()
	}
	out.InstanceMetadata = in.InstanceMetadata
	out.NodeMetadata = in.NodeMetadata
	if in.ConditionHistory != nil {
		in, out := &in.ConditionHistory, &out.ConditionHistory
		*out = make([]ConditionRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]PodRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OOMKills != nil {
		in, out := &in.OOMKills, &out.OOMKills
		*out = make([]OOMKillRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PDBViolations != nil {
		in, out := &in.PDBViolations, &out.PDBViolations
		*out = make([]PDBViolationRecord, len(*in))
		copy(*out, *in)
	}
	in.Archival.DeepCopyInto(&out.Archival)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReportSpec.
func (in *NodeReportSpec) DeepCopy() *NodeReportSpec {
	if in == nil {
		return nil
	}
	out := new(NodeReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReportStatus) DeepCopyInto(out *NodeReportStatus) {
	*out = *in
	if in.CollectionCompletedAt != nil {
		in, out := &in.CollectionCompletedAt, &out.CollectionCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NodeReportStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReportStatus.
func (in *NodeReportStatus) DeepCopy() *NodeReportStatus {
	if in == nil {
		return nil
	}
	out := new(NodeReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReportStatusCondition) DeepCopyInto(out *NodeReportStatusCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReportStatusCondition.
func (in *NodeReportStatusCondition) DeepCopy() *NodeReportStatusCondition {
	if in == nil {
		return nil
	}
	out := new(NodeReportStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOMKillRecord) DeepCopyInto(out *OOMKillRecord) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOMKillRecord.
func (in *OOMKillRecord) DeepCopy() *OOMKillRecord {
	if in == nil {
		return nil
	}
	out := new(OOMKillRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBViolationRecord) DeepCopyInto(out *PDBViolationRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBViolationRecord.
func (in *PDBViolationRecord) DeepCopy() *PDBViolationRecord {
	if in == nil {
		return nil
	}
	out := new(PDBViolationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRecord) DeepCopyInto(out *PodRecord) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRecord.
func (in *PodRecord) DeepCopy() *PodRecord {
	if in == nil {
		return nil
	}
	out := new(PodRecord)
	in.DeepCopyInto(out)
	return out
}
